version: '3.9'

services:
  django:
    container_name: back_django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    volumes:
      - .:/apocalipse/apocalise_api
    ports:
      - "8000:8000"
  

  front:
    container_name: front
    build:
      context: .
      dockerfile: ./compose/front/Dockerfile
    volumes:
      - .:/apocalipse/apocalise_vue
    ports:
      - "8080:8080"